# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.java.installations.auto-download=true
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.2
loom_version=1.16.3
# Mod Properties
mod_version=1.0-SNAPSHOT
maven_group=org.browsit
archives_base_name=fabricConversationsMod
# Dependencies
# check these on https://fabricmc.net/develop
# compile-only, never shipped or required at runtime
fabric_version=0.161.0+26.2
conversation_version=-SNAPSHOT